"""
Django settings for payment_processor project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PRIVATE_KEY = "-----BEGIN RSA PRIVATE KEY-----\nMIICWwIBAAKBgH7xy+jXD0y9Pa3rLmGG8NA6qGTHDhm2NEpPlZcCZ8i1nHb3AiGA\nm4XImGQASsptpqmuOcdA737Jj5OPrig7YBGmt2vrARIjy0FjcqqCwAmj7IQvUzV1\nI9QtOlywUYZbBai3uE6Qo52Hh7Cyz65SIp9KkNBFCu6PqrpfEI6y9ze9AgMBAAEC\ngYB3cE1o0CAHFe7YmnTTMkGVyfryhw9PRc3BNUwL/yljAO0sSY/psbWilHA9dsDn\n4W90KwcV4JT19/Ns5Tz5gZQK5xCSP0lBtYuH8qmiFnJhQ9P8FHy1XeqM5T+5YJOq\nUXcwes2iyRps9BGLpZPhxznq8Qkfyoo92jC0PodHGT5XQQJBAO46MVPjXmyiWwa7\nOgVOg+WguxkVNP/M5JSwevJ/0bpCA+1u8AceubYtc7QBDG1di9Jh1bCBRJumgH3v\nClm9MBkCQQCIakI0fbnU6evTMLK5sMMFZGv/DDczGrEfVzIXcOSw91DJEMaGaJvI\nyij4qiZ1w4wryMcq2lIgh0JX/J5YF2lFAkEA2OaW/wAnetWf91MEksxX/v0HHOFY\nLgdJn6/HYX/LXsC4frfhRzpMcHiVvjCuNe1UXyrAu0IXS3ifyQmZ7Pb6EQJAMz6P\nbj6Ij4XsM+KIUR8os57cvuus1MLDJL3RsGKVVjEhpNZrbVRgqRXgPEFWv0hdIJmE\n0AFBdry43GqmZPsubQJAQCRVku5juz3jI9VN7GE5FEJ5MIbjNralZcKA2plssM3c\n9x5EtHmm51GrGLPkzDkwUrks0KvQ7a54jwrUi+N0RA==\n-----END RSA PRIVATE KEY-----\n"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w$24b$6$_6cjtu$is&o6!lilbwael%yy@4=@weg^e^^h7)aup@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'processor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'payment_processor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'payment_processor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Bank',  # Replace with your database name
        'USER': 'postgres',       # Replace with your PostgreSQL username
        'PASSWORD': 'root',   # Replace with your PostgreSQL password
        'HOST': '127.0.0.1',           # Set to 'localhost' if running locally
        'PORT': '5432',                # Default PostgreSQL port
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
